### ISSUE TITLE
RuntimeError: CUDA error: peer mapping resources exhausted after I use 16GPUs

### ISSUE THREAD

**Issue by thucz** [dcharatan/pixelsplat#13]
I tried to run the script with 16GPUs. But I get the following error. Do you have any clue?

```
Traceback (most recent call last):
  File "/group/30042/ozhengchen/scene_gen/pixelsplat_diff/src/main.py", line 149, in train
    trainer.fit(model_wrapper, datamodule=data_module, ckpt_path=checkpoint_path)
  File "/group/30042/ozhengchen/ft_local/anaconda3/envs/pixelsplat/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/group/30042/ozhengchen/ft_local/anaconda3/envs/pixelsplat/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/group/30042/ozhengchen/ft_local/anaconda3/envs/pixelsplat/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/group/30042/ozhengchen/ft_local/anaconda3/envs/pixelsplat/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/group/30042/ozhengchen/ft_local/anaconda3/envs/pixelsplat/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 965, in _run
    self.strategy.setup(self)
  File "/group/30042/ozhengchen/ft_local/anaconda3/envs/pixelsplat/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 156, in setup
    self.model_to_device()
  File "/group/30042/ozhengchen/ft_local/anaconda3/envs/pixelsplat/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 314, in model_to_device
    self.model.to(self.root_device)
  File "/group/30042/ozhengchen/ft_local/anaconda3/envs/pixelsplat/lib/python3.10/site-packages/lightning_fabric/utilities/device_dtype_mixin.py", line 54, in to
    return super().to(*args, **kwargs)
  File "/group/30042/ozhengchen/ft_local/anaconda3/envs/pixelsplat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/group/30042/ozhengchen/ft_local/anaconda3/envs/pixelsplat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/group/30042/ozhengchen/ft_local/anaconda3/envs/pixelsplat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/group/30042/ozhengchen/ft_local/anaconda3/envs/pixelsplat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 6 more times]
  File "/group/30042/ozhengchen/ft_local/anaconda3/envs/pixelsplat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/group/30042/ozhengchen/ft_local/anaconda3/envs/pixelsplat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: peer mapping resources exhausted
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace
```

**Comment by dcharatan** [comment]
I've only ever tried to run the code on a single machine with up to 8 GPUs, and I've never run into this. Since this code uses PyTorch Lightning for DDP, you would probably have to modify the trainer setup [here](https://github.com/dcharatan/pixelsplat/blob/a0050e1e052bb0eb5dab06c2bbd6be2c4bfc6225/src/main.py#L89-L102) somehow. I would imagine the issue is common to any code base running PyTorch Lightning. Sorry I can't be more helpful!

**Comment by thucz** [comment]
Thanks!
