### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by ZJWdk** [dcharatan/pixelsplat#95]
Hello, thanks for your excellent job! When I was running the command
`python3 -m src.main +experiment=re10k mode=test dataset/view_sampler=evaluation dataset.view_sampler.index_path=assets/evaluation_index_re10k.json checkpointing.load=checkpoints/re10k.ckpt`
on a compute node of a SLURM cluster, I encountered such problem:
`KeyError: 'SLURM_NODEID'`. It suggested me to prepend the commandwith `srun`. I did so, and another error occured:
`socket.gaierror: [Errno -2] Name or service not known`.
I tried your solution in another issue(https://github.com/dcharatan/pixelsplat/issues/72#issuecomment-2105953493), which yielded the same socket.gaierror.
Maybe the problem originates from an attempt to load models from the Internet, while the compute node of a SLURM cluster is not allowed to have access to the Internet? I have confirmed that the code cannot reach behind this line: https://github.com/dcharatan/pixelsplat/blob/dea327d24820b59c5293677fc1f5e6557617430d/src/model/encoder/__init__.py#L17, but I couldn't find out where did the error exactly occur, since the Traceback didn't show where the package `requests` was called. Hopefully you can help me fix this.
I'm posting the complete information below.
```bash
Saving outputs to /public/home/zhaoyq/LN/pixelsplat/outputs/2024-09-16/17-41-21.
rm: 无法删除"outputs/local": 没有那个文件或目录
[2024-09-16 17:41:22,162][py.warnings][WARNING] - /public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/lightning/fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python3 /public/home/zhaoyq/LN/pixelsplat/src/main.py +expe ...

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Before get_encoder
before encoder
Error executing job with overrides: ['+experiment=re10k', 'mode=test', 'dataset/view_sampler=evaluation', 'dataset.view_sampler.index_path=assets/evaluation_index_re10k.json', 'checkpointing.load=checkpoints/re10k.ckpt']
Traceback (most recent call last):
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/public/home/zhaoyq/LN/pixelsplat/src/main.py", line 140, in <module>
    train()
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/public/home/zhaoyq/LN/pixelsplat/src/main.py", line 110, in train
    encoder, encoder_visualizer = get_encoder(cfg.model.encoder)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/jaxtyping/_decorator.py", line 522, in wrapped_fn
    return wrapped_fn_impl(args, kwargs, bound, memos)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/jaxtyping/_decorator.py", line 449, in wrapped_fn_impl
    out = fn(*args, **kwargs)
  File "/public/home/zhaoyq/LN/pixelsplat/src/model/encoder/__init__.py", line 18, in get_encoder
    encoder = encoder(cfg)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/jaxtyping/_decorator.py", line 522, in wrapped_fn
    return wrapped_fn_impl(args, kwargs, bound, memos)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/jaxtyping/_decorator.py", line 449, in wrapped_fn_impl
    out = fn(*args, **kwargs)
  File "/public/home/zhaoyq/LN/pixelsplat/src/model/encoder/encoder_epipolar.py", line 60, in __init__
    self.backbone = get_backbone(cfg.backbone, 3)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/jaxtyping/_decorator.py", line 522, in wrapped_fn
    return wrapped_fn_impl(args, kwargs, bound, memos)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/jaxtyping/_decorator.py", line 449, in wrapped_fn_impl
    out = fn(*args, **kwargs)
  File "/public/home/zhaoyq/LN/pixelsplat/src/model/encoder/backbone/__init__.py", line 16, in get_backbone
    return BACKBONES[cfg.name](cfg, d_in)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/jaxtyping/_decorator.py", line 522, in wrapped_fn
    return wrapped_fn_impl(args, kwargs, bound, memos)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/jaxtyping/_decorator.py", line 449, in wrapped_fn_impl
    out = fn(*args, **kwargs)
  File "/public/home/zhaoyq/LN/pixelsplat/src/model/encoder/backbone/backbone_dino.py", line 25, in __init__
    self.dino = torch.hub.load("facebookresearch/dino:main", cfg.model)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/torch/hub.py", line 539, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/torch/hub.py", line 203, in _get_cache_or_reload
    _validate_not_a_forked_repo(repo_owner, repo_name, ref)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/torch/hub.py", line 162, in _validate_not_a_forked_repo
    response = json.loads(_read_url(Request(url, headers=headers)))
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/site-packages/torch/hub.py", line 145, in _read_url
    with urlopen(url) as r:
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/public/home/zhaoyq/anaconda3/envs/pixelSplat/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by ZJWdk** [comment]
I was mistaken. It won't be a problem anymore.
